#ifndef GLINKRIGHTHANDHOLDINGHYLIANSHIELDDL_H
#define GLINKRIGHTHANDHOLDINGHYLIANSHIELDDL_H

#include "ultra64.h"
#include "object_link_boy.h"

extern u64 gLinkRightHandHoldingHylianShieldDL_gHylianShieldDesignTex_rgba16_png_002_i8[];
extern u64 gLinkRightHandHoldingHylianShieldDL_gLinkAdultShieldHandleTex_ci8_tlut_gLinkAdultTLUT5_png_002_i8[];
extern u64 gLinkRightHandHoldingHylianShieldDL_gLinkAdultDefaultGauntlet1Tex_ci8_tlut_gLinkAdultTLUT5_png_007_i8[];
extern u64 gLinkRightHandHoldingHylianShieldDL_gLinkAdultDefaultGauntlet2Tex_ci8_tlut_gLinkAdultTLUT5_png_007_i8[];
extern u64 gLinkRightHandHoldingHylianShieldDL_gLinkAdultClosedHandThumbTex_ci8_tlut_gLinkAdultTLUT6_png_005_i8[];
extern u64 gLinkRightHandHoldingHylianShieldDL_gLinkAdultHylianShieldBackTex_ci8_tlut_gLinkAdultTLUT4_png_002_i8[];
extern u64 gLinkRightHandHoldingHylianShieldDL_gLinkAdultClosedHandSideTex_ci8_tlut_gLinkAdultTLUT6_png_005_i8[];
extern u64 gLinkRightHandHoldingHylianShieldDL_gLinkAdultHandTex_ci8_tlut_gLinkAdultTLUT6_png_007_i8[];
extern Vtx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_vtx_0[30];
extern Gfx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_tri_0[];
extern Vtx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_vtx_1[18];
extern Gfx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_tri_1[];
extern Vtx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_vtx_2[39];
extern Gfx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_tri_2[];
extern Vtx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_vtx_3[12];
extern Gfx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_tri_3[];
extern Vtx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_vtx_4[3];
extern Gfx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_tri_4[];
extern Vtx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_vtx_5[11];
extern Gfx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_tri_5[];
extern Vtx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_vtx_6[3];
extern Gfx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_tri_6[];
extern Vtx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_vtx_7[15];
extern Gfx gLinkRightHandHoldingHylianShieldDL_gLinkRightHandHoldingHylianShieldDL_mesh_layer_Opaque_tri_7[];
extern Gfx mat_gLinkRightHandHoldingHylianShieldDL_f3dlite_material_051_layerOpaque[];
extern Gfx mat_gLinkRightHandHoldingHylianShieldDL_f3dlite_material_052_layerOpaque[];
extern Gfx mat_gLinkRightHandHoldingHylianShieldDL_f3dlite_material_053_layerOpaque[];
extern Gfx mat_gLinkRightHandHoldingHylianShieldDL_f3dlite_material_054_layerOpaque[];
extern Gfx mat_gLinkRightHandHoldingHylianShieldDL_f3dlite_material_055_layerOpaque[];
extern Gfx mat_gLinkRightHandHoldingHylianShieldDL_f3dlite_material_056_layerOpaque[];
extern Gfx mat_gLinkRightHandHoldingHylianShieldDL_f3dlite_material_057_layerOpaque[];
extern Gfx mat_gLinkRightHandHoldingHylianShieldDL_f3dlite_material_058_layerOpaque[];
extern Gfx gLinkRightHandHoldingHylianShieldDL_opaque_dl[];

#endif
