#ifndef GLINKLEFTHANDCLOSEDDL_H
#define GLINKLEFTHANDCLOSEDDL_H

#include "ultra64.h"
#include "object_link_boy.h"

extern u64 gLinkLeftHandClosedDL_gLinkAdultDefaultGauntlet1Tex_ci8_tlut_gLinkAdultTLUT5_png_005_i8[];
extern u64 gLinkLeftHandClosedDL_gLinkAdultDefaultGauntlet2Tex_ci8_tlut_gLinkAdultTLUT5_png_005_i8[];
extern u64 gLinkLeftHandClosedDL_gLinkAdultClosedHandThumbTex_ci8_tlut_gLinkAdultTLUT6_png_003_i8[];
extern u64 gLinkLeftHandClosedDL_gLinkAdultClosedHandSideTex_ci8_tlut_gLinkAdultTLUT6_png_003_i8[];
extern u64 gLinkLeftHandClosedDL_gLinkAdultHandTex_ci8_tlut_gLinkAdultTLUT6_png_005_i8[];
extern Vtx gLinkLeftHandClosedDL_gLinkLeftHandClosedDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gLinkLeftHandClosedDL_gLinkLeftHandClosedDL_mesh_layer_Opaque_vtx_0[33];
extern Gfx gLinkLeftHandClosedDL_gLinkLeftHandClosedDL_mesh_layer_Opaque_tri_0[];
extern Vtx gLinkLeftHandClosedDL_gLinkLeftHandClosedDL_mesh_layer_Opaque_vtx_1[17];
extern Gfx gLinkLeftHandClosedDL_gLinkLeftHandClosedDL_mesh_layer_Opaque_tri_1[];
extern Vtx gLinkLeftHandClosedDL_gLinkLeftHandClosedDL_mesh_layer_Opaque_vtx_2[3];
extern Gfx gLinkLeftHandClosedDL_gLinkLeftHandClosedDL_mesh_layer_Opaque_tri_2[];
extern Vtx gLinkLeftHandClosedDL_gLinkLeftHandClosedDL_mesh_layer_Opaque_vtx_3[3];
extern Gfx gLinkLeftHandClosedDL_gLinkLeftHandClosedDL_mesh_layer_Opaque_tri_3[];
extern Vtx gLinkLeftHandClosedDL_gLinkLeftHandClosedDL_mesh_layer_Opaque_vtx_4[15];
extern Gfx gLinkLeftHandClosedDL_gLinkLeftHandClosedDL_mesh_layer_Opaque_tri_4[];
extern Gfx mat_gLinkLeftHandClosedDL_f3dlite_material_025_layerOpaque[];
extern Gfx mat_gLinkLeftHandClosedDL_f3dlite_material_026_layerOpaque[];
extern Gfx mat_gLinkLeftHandClosedDL_f3dlite_material_027_layerOpaque[];
extern Gfx mat_gLinkLeftHandClosedDL_f3dlite_material_028_layerOpaque[];
extern Gfx mat_gLinkLeftHandClosedDL_f3dlite_material_029_layerOpaque[];
extern Gfx gLinkLeftHandClosedDL_opaque_dl[];

#endif
