#ifndef GLINKLEFTHANDHOLDINGMASTERSWORDNEARDL_H
#define GLINKLEFTHANDHOLDINGMASTERSWORDNEARDL_H

#include "ultra64.h"
#include "object_link_boy.h"

extern u64 gLinkLeftHandHoldingMasterSwordNearDL_gHilite1Tex_rgba16_png_001_i8[];
extern u64 gLinkLeftHandHoldingMasterSwordNearDL_gLinkAdultSwordPommelTex_ci8_tlut_gLinkAdultTLUT4_png_001_i8[];
extern u64 gLinkLeftHandHoldingMasterSwordNearDL_gLinkAdultSwordGuardTex_ci8_tlut_gLinkAdultTLUT4_png_001_i8[];
extern u64 gLinkLeftHandHoldingMasterSwordNearDL_gLinkAdultSwordEmblemTex_ci8_tlut_gLinkAdultTLUT4_png_001_i8[];
extern u64 gLinkLeftHandHoldingMasterSwordNearDL_gLinkAdultDefaultGauntlet1Tex_ci8_tlut_gLinkAdultTLUT5_png_001_i8[];
extern u64 gLinkLeftHandHoldingMasterSwordNearDL_gLinkAdultDefaultGauntlet2Tex_ci8_tlut_gLinkAdultTLUT5_png_001_i8[];
extern u64 gLinkLeftHandHoldingMasterSwordNearDL_gLinkAdultClosedHandThumbTex_ci8_tlut_gLinkAdultTLUT6_png_001_i8[];
extern u64 gLinkLeftHandHoldingMasterSwordNearDL_gLinkAdultClosedHandSideTex_ci8_tlut_gLinkAdultTLUT6_png_001_i8[];
extern u64 gLinkLeftHandHoldingMasterSwordNearDL_gLinkAdultHandTex_ci8_tlut_gLinkAdultTLUT6_png_001_i8[];
extern Vtx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_vtx_0[59];
extern Gfx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_tri_0[];
extern Vtx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_vtx_1[28];
extern Gfx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_tri_1[];
extern Vtx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_vtx_2[83];
extern Gfx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_tri_2[];
extern Vtx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_vtx_3[18];
extern Gfx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_tri_3[];
extern Vtx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_vtx_4[38];
extern Gfx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_tri_4[];
extern Vtx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_vtx_5[12];
extern Gfx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_tri_5[];
extern Vtx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_vtx_6[3];
extern Gfx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_tri_6[];
extern Vtx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_vtx_7[3];
extern Gfx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_tri_7[];
extern Vtx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_vtx_8[15];
extern Gfx gLinkLeftHandHoldingMasterSwordNearDL_gLinkLeftHandHoldingMasterSwordNearDL_mesh_layer_Opaque_tri_8[];
extern Gfx mat_gLinkLeftHandHoldingMasterSwordNearDL_f3dlite_material_001_layerOpaque[];
extern Gfx mat_gLinkLeftHandHoldingMasterSwordNearDL_f3dlite_material_002_layerOpaque[];
extern Gfx mat_gLinkLeftHandHoldingMasterSwordNearDL_f3dlite_material_003_layerOpaque[];
extern Gfx mat_gLinkLeftHandHoldingMasterSwordNearDL_f3dlite_material_004_layerOpaque[];
extern Gfx mat_gLinkLeftHandHoldingMasterSwordNearDL_f3dlite_material_005_layerOpaque[];
extern Gfx mat_gLinkLeftHandHoldingMasterSwordNearDL_f3dlite_material_006_layerOpaque[];
extern Gfx mat_gLinkLeftHandHoldingMasterSwordNearDL_f3dlite_material_007_layerOpaque[];
extern Gfx mat_gLinkLeftHandHoldingMasterSwordNearDL_f3dlite_material_008_layerOpaque[];
extern Gfx mat_gLinkLeftHandHoldingMasterSwordNearDL_f3dlite_material_009_layerOpaque[];
extern Gfx gLinkLeftHandHoldingMasterSwordNearDL_opaque_dl[];

#endif
