#ifndef GLINKMASTERSWORDANDSHEATHDL_H
#define GLINKMASTERSWORDANDSHEATHDL_H

#include "ultra64.h"
#include "object_link_boy.h"

extern u64 gLinkMasterSwordAndSheathDL_gLinkAdultSheathTex_ci8_tlut_gLinkAdultTLUT4_png_002_i8[];
extern u64 gLinkMasterSwordAndSheathDL_gLinkAdultSheathBandTex_ci8_tlut_gLinkAdultTLUT4_png_002_i8[];
extern u64 gLinkMasterSwordAndSheathDL_gLinkAdultSwordPommelTex_ci8_tlut_gLinkAdultTLUT4_png_004_i8[];
extern u64 gLinkMasterSwordAndSheathDL_gLinkAdultSwordGuardTex_ci8_tlut_gLinkAdultTLUT4_png_004_i8[];
extern Vtx gLinkMasterSwordAndSheathDL_gLinkMasterSwordAndSheathDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gLinkMasterSwordAndSheathDL_gLinkMasterSwordAndSheathDL_mesh_layer_Opaque_vtx_0[18];
extern Gfx gLinkMasterSwordAndSheathDL_gLinkMasterSwordAndSheathDL_mesh_layer_Opaque_tri_0[];
extern Vtx gLinkMasterSwordAndSheathDL_gLinkMasterSwordAndSheathDL_mesh_layer_Opaque_vtx_1[16];
extern Gfx gLinkMasterSwordAndSheathDL_gLinkMasterSwordAndSheathDL_mesh_layer_Opaque_tri_1[];
extern Vtx gLinkMasterSwordAndSheathDL_gLinkMasterSwordAndSheathDL_mesh_layer_Opaque_vtx_2[29];
extern Gfx gLinkMasterSwordAndSheathDL_gLinkMasterSwordAndSheathDL_mesh_layer_Opaque_tri_2[];
extern Vtx gLinkMasterSwordAndSheathDL_gLinkMasterSwordAndSheathDL_mesh_layer_Opaque_vtx_3[90];
extern Gfx gLinkMasterSwordAndSheathDL_gLinkMasterSwordAndSheathDL_mesh_layer_Opaque_tri_3[];
extern Gfx mat_gLinkMasterSwordAndSheathDL_f3dlite_material_047_layerOpaque[];
extern Gfx mat_gLinkMasterSwordAndSheathDL_f3dlite_material_048_layerOpaque[];
extern Gfx mat_gLinkMasterSwordAndSheathDL_f3dlite_material_049_layerOpaque[];
extern Gfx mat_gLinkMasterSwordAndSheathDL_f3dlite_material_050_layerOpaque[];
extern Gfx gLinkMasterSwordAndSheathDL_opaque_dl[];

#endif
