#ifndef GLINKHYLIANSHIELDSWORDANDSHEATHDL_H
#define GLINKHYLIANSHIELDSWORDANDSHEATHDL_H

#include "ultra64.h"
#include "object_link_boy.h"

extern u64 gLinkHylianShieldSwordAndSheathDL_gHylianShieldDesignTex_rgba16_png_001_i8[];
extern u64 gLinkHylianShieldSwordAndSheathDL_gLinkAdultShieldHandleTex_ci8_tlut_gLinkAdultTLUT5_png_001_i8[];
extern u64 gLinkHylianShieldSwordAndSheathDL_gLinkAdultHylianShieldBackTex_ci8_tlut_gLinkAdultTLUT4_png_001_i8[];
extern u64 gLinkHylianShieldSwordAndSheathDL_gLinkAdultSwordPommelTex_ci8_tlut_gLinkAdultTLUT4_png_003_i8[];
extern u64 gLinkHylianShieldSwordAndSheathDL_gLinkAdultSwordGuardTex_ci8_tlut_gLinkAdultTLUT4_png_003_i8[];
extern u64 gLinkHylianShieldSwordAndSheathDL_gLinkAdultSheathTex_ci8_tlut_gLinkAdultTLUT4_png_001_i8[];
extern u64 gLinkHylianShieldSwordAndSheathDL_gLinkAdultSheathBandTex_ci8_tlut_gLinkAdultTLUT4_png_001_i8[];
extern Vtx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_vtx_0[32];
extern Gfx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_tri_0[];
extern Vtx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_vtx_1[18];
extern Gfx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_tri_1[];
extern Vtx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_vtx_2[11];
extern Gfx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_tri_2[];
extern Vtx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_vtx_3[29];
extern Gfx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_tri_3[];
extern Vtx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_vtx_4[91];
extern Gfx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_tri_4[];
extern Vtx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_vtx_5[18];
extern Gfx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_tri_5[];
extern Vtx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_vtx_6[16];
extern Gfx gLinkHylianShieldSwordAndSheathDL_gLinkHylianShieldSwordAndSheathDL_mesh_layer_Opaque_tri_6[];
extern Gfx mat_gLinkHylianShieldSwordAndSheathDL_f3dlite_material_035_layerOpaque[];
extern Gfx mat_gLinkHylianShieldSwordAndSheathDL_f3dlite_material_041_layerOpaque[];
extern Gfx mat_gLinkHylianShieldSwordAndSheathDL_f3dlite_material_042_layerOpaque[];
extern Gfx mat_gLinkHylianShieldSwordAndSheathDL_f3dlite_material_043_layerOpaque[];
extern Gfx mat_gLinkHylianShieldSwordAndSheathDL_f3dlite_material_044_layerOpaque[];
extern Gfx mat_gLinkHylianShieldSwordAndSheathDL_f3dlite_material_045_layerOpaque[];
extern Gfx mat_gLinkHylianShieldSwordAndSheathDL_f3dlite_material_046_layerOpaque[];
extern Gfx gLinkHylianShieldSwordAndSheathDL_opaque_dl[];

#endif
