#ifndef GLINKRIGHTHANDCLOSEDDL_H
#define GLINKRIGHTHANDCLOSEDDL_H

#include "ultra64.h"
#include "object_link_boy.h"

extern u64 gLinkRightHandClosedDL_gLinkAdultDefaultGauntlet1Tex_ci8_tlut_gLinkAdultTLUT5_png_006_i8[];
extern u64 gLinkRightHandClosedDL_gLinkAdultDefaultGauntlet2Tex_ci8_tlut_gLinkAdultTLUT5_png_006_i8[];
extern u64 gLinkRightHandClosedDL_gLinkAdultClosedHandThumbTex_ci8_tlut_gLinkAdultTLUT6_png_004_i8[];
extern u64 gLinkRightHandClosedDL_gLinkAdultClosedHandSideTex_ci8_tlut_gLinkAdultTLUT6_png_004_i8[];
extern u64 gLinkRightHandClosedDL_gLinkAdultHandTex_ci8_tlut_gLinkAdultTLUT6_png_006_i8[];
extern Vtx gLinkRightHandClosedDL_gLinkRightHandClosedDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gLinkRightHandClosedDL_gLinkRightHandClosedDL_mesh_layer_Opaque_vtx_0[39];
extern Gfx gLinkRightHandClosedDL_gLinkRightHandClosedDL_mesh_layer_Opaque_tri_0[];
extern Vtx gLinkRightHandClosedDL_gLinkRightHandClosedDL_mesh_layer_Opaque_vtx_1[12];
extern Gfx gLinkRightHandClosedDL_gLinkRightHandClosedDL_mesh_layer_Opaque_tri_1[];
extern Vtx gLinkRightHandClosedDL_gLinkRightHandClosedDL_mesh_layer_Opaque_vtx_2[3];
extern Gfx gLinkRightHandClosedDL_gLinkRightHandClosedDL_mesh_layer_Opaque_tri_2[];
extern Vtx gLinkRightHandClosedDL_gLinkRightHandClosedDL_mesh_layer_Opaque_vtx_3[3];
extern Gfx gLinkRightHandClosedDL_gLinkRightHandClosedDL_mesh_layer_Opaque_tri_3[];
extern Vtx gLinkRightHandClosedDL_gLinkRightHandClosedDL_mesh_layer_Opaque_vtx_4[15];
extern Gfx gLinkRightHandClosedDL_gLinkRightHandClosedDL_mesh_layer_Opaque_tri_4[];
extern Gfx mat_gLinkRightHandClosedDL_f3dlite_material_030_layerOpaque[];
extern Gfx mat_gLinkRightHandClosedDL_f3dlite_material_031_layerOpaque[];
extern Gfx mat_gLinkRightHandClosedDL_f3dlite_material_032_layerOpaque[];
extern Gfx mat_gLinkRightHandClosedDL_f3dlite_material_033_layerOpaque[];
extern Gfx mat_gLinkRightHandClosedDL_f3dlite_material_034_layerOpaque[];
extern Gfx gLinkRightHandClosedDL_opaque_dl[];

#endif
